class_names:
- a
- b
- c
- d
- e
- f
- g
- h
- i
- j
- k
- l
- m
- n
- o
- p
- q
- r
- s
- t
- u
- v
- w
- x
- y
- z
class_to_idx:
  a: 0
  b: 1
  c: 2
  d: 3
  e: 4
  f: 5
  g: 6
  h: 7
  i: 8
  j: 9
  k: 10
  l: 11
  m: 12
  n: 13
  o: 14
  p: 15
  q: 16
  r: 17
  s: 18
  t: 19
  u: 20
  v: 21
  w: 22
  x: 23
  y: 24
  z: 25
data_paths:
- class_idx: 1
  class_name: b
  files:
  - 1768640512501_B__1_.jpeg
  - 1768640512501_B__2_.jpeg
  - 1768640512501_B__3_.jpeg
  - 1768702847759_B__1_.jpeg
  - 1768702847759_B__2_.jpeg
  - 1768702847759_B__3_.jpeg
  - 1768702847759_IMG_20260117_152957023.jpg
  - 1768702847759_IMG_20260117_153754152.jpg
  - 1768702847759_IMG_20260117_154927817.jpg
  - 1768702847759_IMG_20260117_154929757.jpg
  - 1768702847759_IMG_20260117_154931029.jpg
  - 1768702847759_IMG_20260117_154932715.jpg
  - 1768702847759_IMG_20260117_154934458.jpg
  - 1768702847759_IMG_20260117_155801564.jpg
  - 1768702847759_IMG_20260117_155805436.jpg
  - 1768702847759_IMG_20260117_155806875.jpg
  num_samples: 16
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\b
- class_idx: 2
  class_name: c
  files:
  - 1768640514114_C.jpeg
  - 1768640514114_C__1_.jpeg
  - 1768702859376_C.jpeg
  - 1768702859376_C__1_.jpeg
  - 1768702859376_IMG_20260117_153005680.jpg
  - 1768702859376_IMG_20260117_153812306.jpg
  - 1768702859376_IMG_20260117_155116096.jpg
  - 1768702859376_IMG_20260117_155117787.jpg
  - 1768702859376_IMG_20260117_155119241.jpg
  - 1768702859376_IMG_20260117_155121145.jpg
  - 1768702859376_IMG_20260117_155122636.jpg
  - 1768702859376_IMG_20260117_155124216.jpg
  - 1768702859376_IMG_20260117_155125201.jpg
  - 1768702859376_IMG_20260117_155126610.jpg
  - 1768702859376_IMG_20260117_155127515.jpg
  - 1768702859376_IMG_20260117_155813625.jpg
  num_samples: 16
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\c
- class_idx: 3
  class_name: d
  files:
  - 1768640515435_D__1_.jpeg
  - 1768640515435_D__2_.jpeg
  - 1768640515435_D__3_.jpeg
  - 1768702872962_IMG_20260117_155007522.jpg
  - 1768702872962_IMG_20260117_155009520.jpg
  - 1768702872962_IMG_20260117_155136476.jpg
  - 1768702872962_IMG_20260117_155139880.jpg
  - 1768702872962_IMG_20260117_155140860.jpg
  - 1768702872962_IMG_20260117_155143214.jpg
  - 1768702872962_IMG_20260117_155144468.jpg
  - 1768702872962_IMG_20260117_155145965.jpg
  - 1768702872963_D__1_.jpeg
  - 1768702872963_D__2_.jpeg
  - 1768702872963_D__3_.jpeg
  - 1768702872963_IMG_20260117_153015155.jpg
  - 1768702872963_IMG_20260117_153820148.jpg
  - 1768702872963_IMG_20260117_155137546.jpg
  num_samples: 17
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\d
- class_idx: 5
  class_name: f
  files:
  - 1768640516736_F__1_.jpeg
  - 1768640516736_F__2_.jpeg
  - 1768640516736_F__3_.jpeg
  - 1768702878981_F__1_.jpeg
  - 1768702878981_F__2_.jpeg
  - 1768702878981_F__3_.jpeg
  - 1768702878981_IMG_20260117_151311329.jpg
  - 1768702878981_IMG_20260117_153050506.jpg
  - 1768702878981_IMG_20260117_153909586.jpg
  - 1768702878981_IMG_20260117_155232287.jpg
  - 1768702878981_IMG_20260117_155233212.jpg
  - 1768702878981_IMG_20260117_155236120.jpg
  - 1768702878981_IMG_20260117_155245525.jpg
  - 1768702878981_IMG_20260117_155249909.jpg
  - 1768702878981_IMG_20260117_155251992.jpg
  - 1768702878981_IMG_20260117_155253493.jpg
  - 1768702878981_IMG_20260117_155255198.jpg
  num_samples: 17
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\f
- class_idx: 6
  class_name: g
  files:
  - 1768640518229_G.jpeg
  - 1768702884788_IMG_20260117_155315796.jpg
  - 1768702884788_IMG_20260117_155326153.jpg
  - 1768702884788_IMG_20260117_155327040.jpg
  - 1768702884789_G.jpeg
  - 1768702884789_IMG_20260117_151324422.jpg
  - 1768702884789_IMG_20260117_153142120.jpg
  - 1768702884789_IMG_20260117_155319194.jpg
  - 1768702884789_IMG_20260117_155320332.jpg
  - 1768702884789_IMG_20260117_155321500.jpg
  - 1768702884789_IMG_20260117_155322399.jpg
  num_samples: 11
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\g
- class_idx: 7
  class_name: h
  files:
  - 1768640519375_H.jpeg
  - 1768702890563_H.jpeg
  - 1768702890563_IMG_20260117_151329295.jpg
  - 1768702890563_IMG_20260117_153149106.jpg
  - 1768702890563_IMG_20260117_155331632.jpg
  - 1768702890563_IMG_20260117_155332719.jpg
  - 1768702890563_IMG_20260117_155333792.jpg
  - 1768702890563_IMG_20260117_155334878.jpg
  - 1768702890563_IMG_20260117_155335901.jpg
  - 1768702890563_IMG_20260117_155337500.jpg
  - 1768702890563_IMG_20260117_155339479.jpg
  num_samples: 11
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\h
- class_idx: 9
  class_name: j
  files:
  - 1768640520549_J.jpeg
  - 1768702896356_J.jpeg
  num_samples: 2
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\j
- class_idx: 10
  class_name: k
  files:
  - 1768640522398_K.jpeg
  - 1768702897417_K.jpeg
  num_samples: 2
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\k
- class_idx: 11
  class_name: l
  files:
  - 1768640523627_L.jpeg
  - 1768702898513_IMG_20260117_151634200.jpg
  - 1768702898513_IMG_20260117_153301463.jpg
  - 1768702898513_IMG_20260117_155424755.jpg
  - 1768702898513_IMG_20260117_155425858.jpg
  - 1768702898513_IMG_20260117_155426546.jpg
  - 1768702898513_IMG_20260117_155427407.jpg
  - 1768702898513_IMG_20260117_155428317.jpg
  - 1768702898513_IMG_20260117_155429272.jpg
  - 1768702898513_IMG_20260117_155430134.jpg
  - 1768702898513_IMG_20260117_155431021.jpg
  - 1768702898513_IMG_20260117_155431804.jpg
  - 1768702898513_IMG_20260117_160032162.jpg
  - 1768702898513_IMG_20260117_160036132.jpg
  - 1768702898513_L.jpeg
  num_samples: 15
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\l
- class_idx: 12
  class_name: m
  files:
  - 1768640524838_M.jpeg
  - 1768702905683_IMG_20260117_151735071.jpg
  - 1768702905683_IMG_20260117_152449027.jpg
  - 1768702905683_IMG_20260117_152449272.jpg
  - 1768702905683_IMG_20260117_152456844.jpg
  - 1768702905683_IMG_20260117_154256826.jpg
  - 1768702905683_IMG_20260117_155448446.jpg
  - 1768702905683_IMG_20260117_155449277.jpg
  - 1768702905683_IMG_20260117_155449981.jpg
  - 1768702905683_IMG_20260117_155452545.jpg
  - 1768702905683_IMG_20260117_155453252.jpg
  - 1768702905683_IMG_20260117_155454397.jpg
  - 1768702905683_IMG_20260117_155506927.jpg
  - 1768702905683_IMG_20260117_155507741.jpg
  - 1768702905683_IMG_20260117_160049413.jpg
  - 1768702905683_IMG_20260117_160052500.jpg
  - 1768702905683_IMG_20260117_160059188.jpg
  - 1768702905683_IMG_20260117_160100792.jpg
  - 1768702905683_IMG_20260117_160102411.jpg
  - 1768702905683_M.jpeg
  num_samples: 20
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\m
- class_idx: 13
  class_name: n
  files:
  - 1768640526150_N.jpeg
  - 1768702917635_IMG_20260117_151745543.jpg
  - 1768702917635_IMG_20260117_151746250.jpg
  - 1768702917635_IMG_20260117_152505201.jpg
  - 1768702917635_IMG_20260117_155508628.jpg
  - 1768702917635_IMG_20260117_155510734.jpg
  - 1768702917635_IMG_20260117_155511370.jpg
  - 1768702917635_IMG_20260117_155512629.jpg
  - 1768702917635_IMG_20260117_155515291.jpg
  - 1768702917635_IMG_20260117_155517876.jpg
  - 1768702917635_IMG_20260117_155519048.jpg
  - 1768702917635_IMG_20260117_160111914.jpg
  - 1768702917635_IMG_20260117_160115120.jpg
  - 1768702917635_IMG_20260117_160117279.jpg
  - 1768702917635_IMG_20260117_160119441.jpg
  - 1768702917635_N.jpeg
  num_samples: 16
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\n
- class_idx: 15
  class_name: p
  files:
  - 1768640527630_P.jpeg
  - 1768702923787_IMG_20260117_153242124.jpg
  - 1768702923787_IMG_20260117_154244605.jpg
  - 1768702923787_IMG_20260117_155548230.jpg
  - 1768702923787_IMG_20260117_155549032.jpg
  - 1768702923787_IMG_20260117_155550292.jpg
  - 1768702923787_IMG_20260117_155551063.jpg
  - 1768702923787_IMG_20260117_155551815.jpg
  - 1768702923787_IMG_20260117_155553077.jpg
  - 1768702923787_IMG_20260117_155553845.jpg
  - 1768702923787_IMG_20260117_155554707.jpg
  - 1768702923787_IMG_20260117_155555541.jpg
  - 1768702923787_IMG_20260117_155556274.jpg
  - 1768702923787_IMG_20260117_160228599.jpg
  - 1768702923787_IMG_20260117_160229958.jpg
  - 1768702923787_IMG_20260117_160232005.jpg
  - 1768702923787_IMG_20260117_160233744.jpg
  - 1768702923787_IMG_20260117_160235444.jpg
  - 1768702923787_IMG_20260117_160237082.jpg
  - 1768702923787_P.jpeg
  num_samples: 20
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\p
- class_idx: 16
  class_name: q
  files:
  - 1768640528775_Q.jpeg
  - 1768702931290_Q.jpeg
  num_samples: 2
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\q
- class_idx: 17
  class_name: r
  files:
  - 1768640529994_R.jpeg
  - 1768702932766_IMG_20260117_151617744.jpg
  - 1768702932766_IMG_20260117_151844992.jpg
  - 1768702932766_IMG_20260117_151919877.jpg
  - 1768702932766_IMG_20260117_152057805.jpg
  - 1768702932766_IMG_20260117_152154838.jpg
  - 1768702932766_IMG_20260117_152740215.jpg
  - 1768702932766_IMG_20260117_155603909.jpg
  - 1768702932766_IMG_20260117_155606314.jpg
  - 1768702932766_IMG_20260117_155607086.jpg
  - 1768702932766_IMG_20260117_155607815.jpg
  - 1768702932766_IMG_20260117_155608654.jpg
  - 1768702932766_IMG_20260117_155610127.jpg
  - 1768702932766_IMG_20260117_155611023.jpg
  - 1768702932766_IMG_20260117_155611695.jpg
  - 1768702932766_IMG_20260117_155612963.jpg
  - 1768702932766_IMG_20260117_155613933.jpg
  - 1768702932766_IMG_20260117_160252069.jpg
  - 1768702932766_IMG_20260117_160253628.jpg
  - 1768702932766_IMG_20260117_160255991.jpg
  - 1768702932766_IMG_20260117_160257597.jpg
  - 1768702932766_R.jpeg
  num_samples: 22
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\r
- class_idx: 18
  class_name: s
  files:
  - 1768640531047_S.jpeg
  - 1768702940591_IMG_20260117_152216080.jpg
  - 1768702940591_IMG_20260117_152228748.jpg
  - 1768702940591_IMG_20260117_152749556.jpg
  - 1768702940591_IMG_20260117_154147889.jpg
  - 1768702940591_IMG_20260117_155618386.jpg
  - 1768702940591_IMG_20260117_155618976.jpg
  - 1768702940591_IMG_20260117_155620931.jpg
  - 1768702940591_IMG_20260117_155621566.jpg
  - 1768702940591_IMG_20260117_155623498.jpg
  - 1768702940591_IMG_20260117_155624082.jpg
  - 1768702940591_IMG_20260117_160303260.jpg
  - 1768702940591_IMG_20260117_160305565.jpg
  - 1768702940591_IMG_20260117_160308256.jpg
  - 1768702940591_IMG_20260117_160310136.jpg
  - 1768702940591_IMG_20260117_160325118.jpg
  - 1768702940591_IMG_20260117_160327688.jpg
  - 1768702940591_IMG_20260117_160329805.jpg
  - 1768702940591_IMG_20260117_160331578.jpg
  - 1768702940591_IMG_20260117_160332927.jpg
  - 1768702940592_IMG_20260117_154149592.jpg
  - 1768702940592_IMG_20260117_154212156.jpg
  - 1768702940592_S.jpeg
  num_samples: 23
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\s
- class_idx: 19
  class_name: t
  files:
  - 1768640532107_T.jpeg
  - 1768702948536_IMG_20260117_152319045.jpg
  - 1768702948536_IMG_20260117_152758777.jpg
  - 1768702948536_IMG_20260117_155632732.jpg
  - 1768702948536_IMG_20260117_155634626.jpg
  - 1768702948536_IMG_20260117_155635736.jpg
  - 1768702948536_IMG_20260117_155636453.jpg
  - 1768702948536_IMG_20260117_155637260.jpg
  - 1768702948536_IMG_20260117_155638241.jpg
  - 1768702948536_IMG_20260117_155639036.jpg
  - 1768702948536_T.jpeg
  num_samples: 11
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\t
- class_idx: 21
  class_name: v
  files:
  - 1768640533426_V.jpeg
  - 1768702952275_IMG_20260117_152411615.jpg
  - 1768702952275_IMG_20260117_152824157.jpg
  - 1768702952275_IMG_20260117_154204361.jpg
  - 1768702952275_IMG_20260117_155657596.jpg
  - 1768702952275_IMG_20260117_155658269.jpg
  - 1768702952275_IMG_20260117_155658885.jpg
  - 1768702952275_IMG_20260117_155659635.jpg
  - 1768702952275_IMG_20260117_155700513.jpg
  - 1768702952275_IMG_20260117_155701236.jpg
  - 1768702952275_IMG_20260117_155702495.jpg
  - 1768702952275_IMG_20260117_155703333.jpg
  - 1768702952275_IMG_20260117_155704185.jpg
  - 1768702952275_IMG_20260117_160401466.jpg
  - 1768702952275_IMG_20260117_160404175.jpg
  - 1768702952275_IMG_20260117_160406893.jpg
  - 1768702952275_IMG_20260117_160408183.jpg
  - 1768702952275_IMG_20260117_160409501.jpg
  - 1768702952275_V.jpeg
  num_samples: 19
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\v
- class_idx: 22
  class_name: w
  files:
  - 1768640534652_W.jpeg
  - 1768702957961_IMG_20260117_152416934.jpg
  - 1768702957961_IMG_20260117_152828232.jpg
  - 1768702957961_IMG_20260117_155708662.jpg
  - 1768702957961_IMG_20260117_155709282.jpg
  - 1768702957961_IMG_20260117_155710050.jpg
  - 1768702957961_IMG_20260117_155714958.jpg
  - 1768702957961_IMG_20260117_155715846.jpg
  - 1768702957961_IMG_20260117_155723113.jpg
  - 1768702957961_IMG_20260117_160414429.jpg
  - 1768702957961_IMG_20260117_160416823.jpg
  - 1768702957961_IMG_20260117_160418193.jpg
  - 1768702957961_IMG_20260117_160422798.jpg
  - 1768702957961_W.jpeg
  num_samples: 14
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\w
- class_idx: 23
  class_name: x
  files:
  - 1768640535673_X.jpeg
  - 1768702964570_X.jpeg
  num_samples: 2
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\x
- class_idx: 24
  class_name: y
  files:
  - 1768640536829_Y.jpeg
  - 1768702965728_Y.jpeg
  num_samples: 2
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\y
- class_idx: 25
  class_name: z
  files:
  - 1768640537932_Z.jpeg
  - 1768702966760_Z.jpeg
  num_samples: 2
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\consonantes\z
- class_idx: 0
  class_name: a
  files:
  - 1768640504993_A__1_.jpeg
  - 1768640504993_A__2_.jpeg
  - 1768640504993_A__3_.jpeg
  - 1768702750660_A__1_.jpeg
  - 1768702750660_A__2_.jpeg
  - 1768702750660_A__3_.jpeg
  - 1768702750660_IMG_20260117_152941488.jpg
  - 1768702750660_IMG_20260117_153736532.jpg
  - 1768702750660_IMG_20260117_154810328.jpg
  - 1768702750660_IMG_20260117_154812053.jpg
  - 1768702750660_IMG_20260117_154817392.jpg
  - 1768702750660_IMG_20260117_154819034.jpg
  - 1768702750660_IMG_20260117_154902044.jpg
  - 1768702750660_IMG_20260117_154902958.jpg
  - 1768702750660_IMG_20260117_154903964.jpg
  - 1768702750660_IMG_20260117_154905001.jpg
  - 1768702750660_IMG_20260117_154906333.jpg
  - 1768702750660_IMG_20260117_155048899.jpg
  - 1768702750660_IMG_20260117_155748768.jpg
  - 1768702750660_IMG_20260117_155750135.jpg
  - 1768702750660_IMG_20260117_155753697.jpg
  num_samples: 21
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\vocales\a
- class_idx: 4
  class_name: e
  files:
  - 1768640506818_E__1_.jpeg
  - 1768640506818_E__2_.jpeg
  - 1768640506818_E__3_.jpeg
  - 1768702774147_E__1_.jpeg
  - 1768702774147_E__2_.jpeg
  - 1768702774147_E__3_.jpeg
  - 1768702774147_IMG_20260117_151259157.jpg
  - 1768702774147_IMG_20260117_153018523.jpg
  - 1768702774147_IMG_20260117_153845138.jpg
  - 1768702774147_IMG_20260117_155152277.jpg
  - 1768702774147_IMG_20260117_155153085.jpg
  - 1768702774147_IMG_20260117_155156196.jpg
  - 1768702774147_IMG_20260117_155157301.jpg
  - 1768702774147_IMG_20260117_155204364.jpg
  - 1768702774147_IMG_20260117_155206929.jpg
  - 1768702774147_IMG_20260117_155214415.jpg
  num_samples: 16
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\vocales\e
- class_idx: 8
  class_name: i
  files:
  - 1768640507938_I.jpeg
  - 1768702807627_I.jpeg
  - 1768702807627_IMG_20260117_151351036.jpg
  - 1768702807627_IMG_20260117_153159584.jpg
  - 1768702807627_IMG_20260117_153205028.jpg
  - 1768702807627_IMG_20260117_155346053.jpg
  - 1768702807627_IMG_20260117_155347719.jpg
  - 1768702807627_IMG_20260117_155348748.jpg
  - 1768702807627_IMG_20260117_155349634.jpg
  - 1768702807627_IMG_20260117_155350527.jpg
  - 1768702807627_IMG_20260117_155352675.jpg
  - 1768702807627_IMG_20260117_155354366.jpg
  - 1768702807627_IMG_20260117_155355897.jpg
  - 1768702807627_IMG_20260117_155357649.jpg
  - 1768702807627_IMG_20260117_155359468.jpg
  num_samples: 15
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\vocales\i
- class_idx: 14
  class_name: o
  files:
  - 1768640509359_O.jpeg
  - 1768702817538_IMG_20260117_151552835.jpg
  - 1768702817538_IMG_20260117_151812366.jpg
  - 1768702817538_IMG_20260117_152514319.jpg
  - 1768702817538_IMG_20260117_154230746.jpg
  - 1768702817538_IMG_20260117_155527355.jpg
  - 1768702817538_IMG_20260117_155529320.jpg
  - 1768702817538_IMG_20260117_155530082.jpg
  - 1768702817538_IMG_20260117_155531077.jpg
  - 1768702817538_IMG_20260117_155531806.jpg
  - 1768702817538_IMG_20260117_155532702.jpg
  - 1768702817538_IMG_20260117_155533516.jpg
  - 1768702817538_IMG_20260117_155535432.jpg
  - 1768702817538_IMG_20260117_160127003.jpg
  - 1768702817538_IMG_20260117_160128497.jpg
  - 1768702817538_IMG_20260117_160130360.jpg
  - 1768702817538_IMG_20260117_160135116.jpg
  - 1768702817538_IMG_20260117_160141680.jpg
  - 1768702817538_IMG_20260117_160146399.jpg
  - 1768702817538_IMG_20260117_160148055.jpg
  - 1768702817538_O.jpeg
  num_samples: 21
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\vocales\o
- class_idx: 20
  class_name: u
  files:
  - 1768640510623_U.jpeg
  - 1768702835669_IMG_20260117_152401915.jpg
  - 1768702835669_IMG_20260117_152818355.jpg
  - 1768702835669_IMG_20260117_154139813.jpg
  - 1768702835669_IMG_20260117_154158483.jpg
  - 1768702835669_IMG_20260117_155646823.jpg
  - 1768702835669_IMG_20260117_155647707.jpg
  - 1768702835669_IMG_20260117_155649270.jpg
  - 1768702835669_IMG_20260117_155650102.jpg
  - 1768702835669_IMG_20260117_155650811.jpg
  - 1768702835669_IMG_20260117_155651927.jpg
  - 1768702835669_IMG_20260117_155652965.jpg
  - 1768702835669_IMG_20260117_160343180.jpg
  - 1768702835669_IMG_20260117_160344820.jpg
  - 1768702835669_IMG_20260117_160346537.jpg
  - 1768702835669_IMG_20260117_160352425.jpg
  - 1768702835669_IMG_20260117_160354220.jpg
  - 1768702835669_IMG_20260117_160356370.jpg
  - 1768702835669_U.jpeg
  num_samples: 19
  path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets\alfabeto\vocales\u
dataset_path: C:\Users\axedu\Documents\Jnaa-Ri-yee\Jnaa-ri-yee\database\datasets
dataset_type: image
num_classes: 26
